<?php include 'includes/header.php'; ?>


<h2> <i class="fas fa-cogs"></i>  Back Office</h2>

<!--<a href="detail.php?id=<?= $article['id'] ?>"> </a>-->

<table>
    <caption>Liste des articles</caption>
    <thead>
        <tr>
            <th>Titre</th>
            <th>Article</th>
            <th>Auteur</th>
            <th>Catégorie</th>
            <th>Modifier</th>
            <th>Supprimer</th>
        </tr>
        
    </thead>
    <tbody>
        <?php foreach($articles as $article) : ?>
        <tr>
            <td> <?= htmlspecialchars($article['title']) ?> </td>
            <td> <?= htmlspecialchars(substr($article['content'] , 0, 49 )) ?> </td>
            <td> <?= htmlspecialchars($article['firstname'])?>  <?= htmlspecialchars($article['lastname'])?> </td>
            <td> <?= $article['nom'] ?> </td>
            <td><a href="edit.php?id=<?= $article['id'] ?>"><i class="fas fa-edit"></i></a></td>
            <td><a href="delete.php?id=<?= $article['id'] ?> "><i class="fas fa-trash-alt"></i></a></td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>




<?php include 'includes/footer.php'; ?>	