<?php include 'includes/header.php'; ?>

		<main>
		    <h2>  <i class="fas fa-file-alt"></i> Les articles    </h2>
		   	<ul class="articles">
		       
		       <?php foreach($articles as $article) : ?>
                	<li>
                		
                    	<h3> <i class="fas fa-hand-point-right"></i> <a  href="detail.php?id=<?= $article['id'] ?>">
                    		 <?= htmlspecialchars($article['title']) ?> </a></h3>
                    	<p> <?= htmlspecialchars(substr($article['content'] , 0, 49 )) ?> [...] </p>
                    	<p> Rédigé le <?= $article['publication_date']  ?>
                    		par <?= htmlspecialchars($article['firstname'])?>  <?= htmlspecialchars($article['lastname'])?> 
            			</p>
                    </li>
                 
            	<?php endforeach ?>
         
		   </ul>
   
		</main>
			
<?php include 'includes/footer.php'; ?>	

