<h3><i class="fas fa-shopping-basket"></i>  Passer une commande</h3>

<form>
    
    <fieldset class="order"> 
        <legend>Ajouter un article</legend>
         
        <select id="product">
             <?php foreach($products as $product) : ?>      
                 <option value="<?= $product['id'] ?>"><?= htmlspecialchars($product['title']) ?></option>
            <?php endforeach ?>    
        </select>    
 </form>       
            <div id="informations">
                <img id="photo" src="" alt="produit">
                <p id="name"></p>
                <p id="description"></p>
                 <p> 
                     <label for="price"> Prix </label>
                     <span id="price"></span> €
                 </p>
                 <p>
                    <label for="quantity"> Quantité </label>
                    <input type="text" id="quantity">
                </p>
            </div>

    <button id="add"class="btn2"> Ajouter </button>
    </fieldset>
    <fieldset class="order"> 
        <legend>Récapitulatif commande</legend>
            <table id="cart">
                <thead>
                    <tr>
                        <th class="number">Quantité</th>
                        <th>Produit</th>
                        <th class="number">Prix Unitaire</th>
                        <th class="number">Prix Total</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
                    
                
            </table>
</fieldset>

<button id="confirm"> Valider </button>

<script src="<?= $wwwUrl ?>/js/order.js"></script>
<script src="<?= $wwwUrl ?>/js/cart.js"></script>
