<!-- Message de notification -->

<!-- Code HTML à écrire -->



<!-- Liste des aliments -->
<table class="generic-table meal-list">
    
        <!-- Code HTML à écrire -->
        
		    <h3>  <i class="fas fa-file-alt"></i> Le menu    </h3>
		   	
		       
		       <?php foreach($products as $product) : ?>
                
                    <tr>
                        <td> <img src="<?= $wwwUrl ?>/images/meals/<?= htmlspecialchars($product['photo']) ?>" 
                        alt="<?= htmlspecialchars($product['photo']) ?>" ></td>
                        
                    	<td> <?= htmlspecialchars($product['title']) ?> </td>
                    	
                    	<td> <?= htmlspecialchars($product['description']) ?> </td>
                    	
                    	<td> <?= htmlspecialchars($product['price']) .' euros'  ?></td>
                    </tr>
                    
                        
                    
            	<?php endforeach ?>
                
                	
         
</table>